Revert to html5ever 0.24
```
$ cargo update -p html5ever
    Updating crates.io index
    Updating html5ever v0.25.1 -> v0.24.1
    Updating markup5ever v0.10.0 -> v0.9.0
    Removing phf v0.8.0
    Removing phf_codegen v0.8.0
    Removing phf_generator v0.8.0
    Removing phf_shared v0.8.0
    Removing rand_pcg v0.2.1
    Removing siphasher v0.3.3
    Updating string_cache v0.8.0 -> v0.7.5
    Updating string_cache_codegen v0.5.1 -> v0.4.4
      Adding string_cache_shared v0.3.0
```

This fixes the following error:

```
error[E0432]: unresolved import `html5ever::rcdom`

 --> tests/harness/suites/html5lib_tests/feedback_tests/expected_tokens.rs:2:16

  |

2 | use html5ever::rcdom::RcDom;

  |                ^^^^^ could not find `rcdom` in `html5ever`

error: aborting due to previous error
```

Long-term, the test should probably switch to using kuchiki or something.