Update dependencies (#73)
* Update Cargo.lock to new lockfile version

Cargo doesn't allow keeping the same lockfile but only changing the
format, so instead this updates walkdir a minor version (2.2.9 -> 2.3.1).

```
$ cargo update -p walkdir
```

* Update html5ever

```
$ cargo update -p html5ever
    Updating crates.io index
    Removing debug_unreachable v0.1.1
    Updating html5ever v0.21.0 -> v0.25.1
    Removing lazy_static v0.2.11
    Removing log v0.3.9
    Updating markup5ever v0.6.2 -> v0.10.0
      Adding phf v0.8.0
      Adding phf_codegen v0.8.0
      Adding phf_generator v0.8.0
      Adding phf_shared v0.8.0
      Adding ppv-lite86 v0.2.9
    Removing quote v0.3.15
      Adding rand v0.7.3
      Adding rand_chacha v0.2.2
      Adding rand_hc v0.2.0
      Adding rand_pcg v0.2.1
      Adding siphasher v0.3.3
    Updating string_cache v0.6.2 -> v0.8.0
    Updating string_cache_codegen v0.4.4 -> v0.5.1
    Removing string_cache_shared v0.3.0
    Removing syn v0.11.11
    Removing synom v0.11.3
    Removing unicode-xid v0.0.4
    Removing unreachable v0.1.1
    Removing void v1.0.2
```

* Update cargo-fuzz, removing dependency on tokio

This commit can be replicated as follows:

```
$ cargo update -p cargo-fuzz
    Updating crates.io index
    Removing bytes v0.4.12
    Updating cargo-fuzz v0.5.4 -> v0.5.5
    Removing fnv v1.0.6
    Removing fuchsia-zircon v0.3.3
    Removing fuchsia-zircon-sys v0.3.3
    Removing futures v0.1.29
    Removing iovec v0.1.4
    Removing lock_api v0.3.1
    Removing mio v0.6.19
    Removing mio-named-pipes v0.1.6
    Removing mio-uds v0.6.7
    Removing miow v0.2.1
    Removing miow v0.3.3
    Removing net2 v0.2.33
    Removing parking_lot v0.9.0
    Removing parking_lot_core v0.6.2
    Removing scoped-tls v0.1.2
    Removing slab v0.4.2
    Removing socket2 v0.3.11
    Removing tokio v0.1.22
    Removing tokio-codec v0.1.1
    Removing tokio-core v0.1.17
    Removing tokio-current-thread v0.1.6
    Removing tokio-executor v0.1.8
    Removing tokio-fs v0.1.6
    Removing tokio-io v0.1.12
    Removing tokio-process v0.1.6
    Removing tokio-reactor v0.1.10
    Removing tokio-signal v0.1.5
    Removing tokio-sync v0.1.7
    Removing tokio-tcp v0.1.3
    Removing tokio-threadpool v0.1.16
    Removing tokio-timer v0.2.11
    Removing tokio-udp v0.1.5
    Removing tokio-uds v0.2.5
    Removing ws2_32-sys v0.2.1
```

* Remove duplicate itertools dependency

* Update cargo-fuzz

```
$ cargo update -p cargo-fuzz
    Updating crates.io index
      Adding anyhow v1.0.33
    Removing backtrace v0.3.40
    Removing backtrace-sys v0.1.32
    Updating cargo-fuzz v0.5.5 -> v0.8.0
    Removing cc v1.0.46
    Removing error-chain v0.12.1
      Adding heck v0.3.1
      Adding proc-macro-error v1.0.4
      Adding proc-macro-error-attr v1.0.4
    Removing rand v0.4.6
    Removing rustc-demangle v0.1.16
      Adding structopt v0.3.20
      Adding structopt-derive v0.4.13
    Removing tempdir v0.3.7
      Adding tempfile v3.1.0
    Updating toml v0.4.10 -> v0.5.7
      Adding unicode-segmentation v1.6.0
    Updating version_check v0.1.5 -> v0.9.2
```

* Revert to html5ever 0.24

```
$ cargo update -p html5ever
    Updating crates.io index
    Updating html5ever v0.25.1 -> v0.24.1
    Updating markup5ever v0.10.0 -> v0.9.0
    Removing phf v0.8.0
    Removing phf_codegen v0.8.0
    Removing phf_generator v0.8.0
    Removing phf_shared v0.8.0
    Removing rand_pcg v0.2.1
    Removing siphasher v0.3.3
    Updating string_cache v0.8.0 -> v0.7.5
    Updating string_cache_codegen v0.5.1 -> v0.4.4
      Adding string_cache_shared v0.3.0
```

This fixes the following error:

```
error[E0432]: unresolved import `html5ever::rcdom`

 --> tests/harness/suites/html5lib_tests/feedback_tests/expected_tokens.rs:2:16

  |

2 | use html5ever::rcdom::RcDom;

  |                ^^^^^ could not find `rcdom` in `html5ever`

error: aborting due to previous error
```

Long-term, the test should probably switch to using kuchiki or something.